version: '3.7'

services:
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    depends_on:
      - wait_for_zookeeper
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_BROKER_ID: 0
      KAFKA_CREATE_TOPICS: "local_jbi_heartbeat:1:1,local_jbi_responses:1:1,local_jbi_commands:1:1,local_filewriter_status:1:1,local_filewriter_pool:1:1,local_jbi_visualisation:1:1,local_filewriter:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:       
      - frontend

  wait_for_zookeeper:
    image: dadarek/wait-for-dependencies
    command: zookeeper:2181
    depends_on:
      - zookeeper
    networks:       
      - frontend

  zookeeper:
    image: zookeeper:3.4
    networks:       
      - frontend
    ports:
      - "2181:2181"

networks:   
  frontend:
