version: '3.5'
services:

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:7.2.1
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - frontend

  kafka1:
    container_name: kafka1
    hostname: kafka1
    image: confluentinc/cp-server:7.2.1
    restart: always
    depends_on:
      - wait_for_zookeeper
    ports:
      - "9092:9092"
      - "9099:9099"
    networks:
      - frontend
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_MESSAGE_MAX_BYTES: 1000000000
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      ## listeners
      KAFKA_LISTENERS: 'BROKERS://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'BROKERS://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'BROKERS:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKERS

  wait_for_zookeeper:
    image: dadarek/wait-for-dependencies
    command: zookeeper:2181
    depends_on:
      - zookeeper
    networks:       
      - frontend

networks:
  frontend:
